class Contentrepository {
  Map<String, dynamic> data = {
    "kr": [
      {
        "cid": "김치찌개",
        "image": "assets/images/김치찌개.jpg",
        "name": "김치찌개",
        "explain": "김치찌개",
        "like": "",
      },
      {
        "cid": "된장찌개",
        "image": "assets/images/된장찌개.jpg",
        "name": "된장찌개",
        "explain": "된장찌개",
        "like": "",
      },
      {
        "cid": "소고기무국",
        "image": "assets/images/소고기무국.jpg",
        "name": "소고기무국",
        "explain": "소고기무국",
        "like": "",
      },
      {
        "cid": "미역국",
        "image": "assets/images/미역국.jpg",
        "name": "미역국",
        "explain": "미역국",
        "like": "",
      },
      {
        "cid": "계란말이",
        "image": "assets/images/계란말이.jpg",
        "name": "계란말이",
        "explain": "계란말이",
        "like": "",
      },
      {
        "cid": "떡볶이",
        "image": "assets/images/떡볶이.jpg",
        "name": "떡볶이",
        "explain": "떡볶이",
        "like": "",
      },
      {
        "cid": "제육볶음",
        "image": "assets/images/제육볶음.jpg",
        "name": "제육볶음",
        "explain": "제육볶음",
        "like": "",
      },
      {
        "cid": "김밥",
        "image": "assets/images/김밥.jpg",
        "name": "김밥",
        "explain": "김밥",
        "like": "",
      },
      {
        "cid": "감자볶음",
        "image": "assets/images/감자볶음.jpg",
        "name": "감자볶음",
        "explain": "감자볶음",
        "like": "",
      },
      {
        "cid": "계란찜",
        "image": "assets/images/계란찜.jpg",
        "name": "계란찜",
        "explain": "계란찜",
        "like": "",
      },
      {
        "cid": "궁중떡볶이",
        "image": "assets/images/궁중떡볶이.jpg",
        "name": "궁중떡볶이",
        "explain": "궁중떡볶이",
        "like": "",
      },
      {
        "cid": "부추겉절이",
        "image": "assets/images/부추겉절이.jpg",
        "name": "부추겉절이",
        "explain": "부추겉절이",
        "like": "",
      },
      {
        "cid": "3",
        "image": "assets/images/소고기무국.jpg",
        "name": "소고기무국",
        "explain": "소고기무국",
        "like": "",
      },
      {
        "cid": "무생채",
        "image": "assets/images/무생채.jpg",
        "name": "무생채",
        "explain": "무생채",
        "like": "",
      },
      {
        "cid": "감자조림",
        "image": "assets/images/감자조림.jpg",
        "name": "감자조림",
        "explain": "감자조림",
        "like": "",
      },
      {
        "cid": "우엉조림",
        "image": "assets/images/우엉조림.jpg",
        "name": "우엉조림",
        "explain": "우엉조림",
        "like": "",
      },
      {
        "cid": "감자전",
        "image": "assets/images/감자전.jpg",
        "name": "감자전",
        "explain": "감자전",
        "like": "",
      },
      {
        "cid": "부추전",
        "image": "assets/images/부추전.jpg",
        "name": "부추전",
        "explain": "부추전",
        "like": "",
      },
      {
        "cid": "제육볶음",
        "image": "assets/images/제육볶음.jpg",
        "name": "제육볶음",
        "explain": "제육볶음",
        "like": "",
      },
      {
        "cid": "불고기",
        "image": "assets/images/불고기.jpg",
        "name": "불고기",
        "explain": "불고기",
        "like": "",
      },
      {
        "cid": "비빔밥",
        "image": "assets/images/비빔밥.jpg",
        "name": "비빔밥",
        "explain": "비빔밥",
        "like": "",
      },
      {
        "cid": "잡채",
        "image": "assets/images/잡채.jpg",
        "name": "잡채",
        "explain": "잡채",
        "like": "",
      },
      {
        "cid": "청경채볶음",
        "image": "assets/images/청경채볶음.jpg",
        "name": "청경채볶음",
        "explain": "청경채볶음",
        "like": "",
      },
      {
        "cid": "오징어볶음",
        "image": "assets/images/오징어볶음.jpg",
        "name": "오징어볶음",
        "explain": "오징어볶음",
        "like": "",
      },
      {
        "cid": "고추장불고기",
        "image": "assets/images/고추장불고기.jpg",
        "name": "고추장불고기",
        "explain": "고추장불고기",
        "like": "",
      },
      {
        "cid": "멸치볶음",
        "image": "assets/images/멸치볶음.jpg",
        "name": "멸치볶음",
        "explain": "멸치볶음",
        "like": "",
      },
      {
        "cid": "김치전",
        "image": "assets/images/김치전.jpg",
        "name": "김치전",
        "explain": "김치전",
        "like": "",
      },
      {
        "cid": "애호박전",
        "image": "assets/images/애호박전.jpg",
        "name": "애호박전",
        "explain": "애호박전",
        "like": "",
      },
      {
        "cid": "두부부침",
        "image": "assets/images/두부부침.jpg",
        "name": "두부부침",
        "explain": "두부부침",
        "like": "",
      },
      {
        "cid": "두부조림",
        "image": "assets/images/두부조림.jpg",
        "name": "두부조림",
        "explain": "두부조림",
        "like": "",
      },
      {
        "cid": "김치제육볶음",
        "image": "assets/images/김치제육볶음.jpg",
        "name": "김치제육 볶음",
        "explain": "김치제육 볶음",
        "like": "",
      },
      {
        "cid": "계란장조림",
        "image": "assets/images/계란장조림.jpg",
        "name": "계란장조림",
        "explain": "계란장조림",
        "like": "",
      },
      {
        "cid": "닭갈비",
        "image": "assets/images/닭갈비.jpg",
        "name": "닭갈비",
        "explain": "닭갈비",
        "like": "",
      },
      {
        "cid": "떡갈비",
        "image": "assets/images/떡갈비.jpg",
        "name": "떡갈비",
        "explain": "떡갈비",
        "like": "",
      },
      {
        "cid": "연근조림",
        "image": "assets/images/연근조림.jpg",
        "name": "연근조림",
        "explain": "연근조림",
        "like": "",
      },
      {
        "cid": "콩나물무침",
        "image": "assets/images/콩나물무침.jpg",
        "name": "콩나물무침",
        "explain": "콩나물무침",
        "like": "",
      },
      {
        "cid": "고등어무조림",
        "image": "assets/images/고등어무조림.jpg",
        "name": "고등어 무조림",
        "explain": "고등어 무조림",
        "like": "",
      },
      {
        "cid": "매운찜갈비",
        "image": "assets/images/매운찜갈비.jpg",
        "name": "매운찜갈비",
        "explain": "매운찜갈비",
        "like": "",
      },
      {
        "cid": "닭볶음탕",
        "image": "assets/images/닭볶음탕.jpg",
        "name": "닭볶음탕",
        "explain": "닭볶음탕",
        "like": "",
      },
      {
        "cid": "감자양배추전",
        "image": "assets/images/감자양배추전.jpg",
        "name": "감자양배추전",
        "explain": "감자양배추전",
        "like": "",
      },
      {
        "cid": "와인삼겹살",
        "image": "assets/images/와인삼겹살.jpg",
        "name": "와인 삼겹살",
        "explain": "와인 삼겹살",
        "like": "",
      },
      {
        "cid": "시금치나물",
        "image": "assets/images/시금치나물.jpg",
        "name": "시금치나물",
        "explain": "시금치나물",
        "like": "",
      },
    ],
    "cn": [
      {
        "cid": "꿔바로우",
        "image": "assets/images/꿔바로우.jpg",
        "name": "꿔바로우 ",
        "explain": "꿔바로우 ",
        "like": "",
      },
      {
        "cid": "짜장면",
        "image": "assets/images/짜장면.jpg",
        "name": "짜장면",
        "explain": "짜장면",
        "like": "",
      },
      {
        "cid": "짬뽕",
        "image": "assets/images/짬뽕.jpg",
        "name": "짬뽕",
        "explain": "짬뽕",
        "like": "",
      },
      {
        "cid": "팔보채",
        "image": "assets/images/팔보채.jpg",
        "name": "팔보채",
        "explain": "팔보채",
        "like": "",
      },
      {
        "cid": "삼선볶음밥",
        "image": "assets/images/삼선볶음밥.jpg",
        "name": "삼선볶음밥",
        "explain": "삼선볶음밥",
        "like": "",
      },
      {
        "cid": "깐쇼새우",
        "image": "assets/images/깐쇼새우.jpg",
        "name": "깐쇼새우",
        "explain": "깐쇼새우",
        "like": "",
      },
      {
        "cid": "동파육",
        "image": "assets/images/동파육.jpg",
        "name": "동파육",
        "explain": "동파육",
        "like": "",
      },
      {
        "cid": "마라샹궈",
        "image": "assets/images/마라샹궈.jpg",
        "name": "마라샹궈",
        "explain": "마라샹궈",
        "like": "",
      },
      {
        "cid": "멘보샤",
        "image": "assets/images/멘보샤.jpg",
        "name": "멘보샤",
        "explain": "멘보샤",
        "like": "",
      },
      {
        "cid": "마파두부",
        "image": "assets/images/마파두부.jpg",
        "name": "마파두부",
        "explain": "마파두부",
        "like": "",
      },
      {
        "cid": "마라탕",
        "image": "assets/images/마라탕.jpg",
        "name": "마라탕",
        "explain": "마라탕",
        "like": "",
      },
      {
        "cid": "쇠고기난자완스",
        "image": "assets/images/쇠고기 난자완스.jpg",
        "name": "쇠고기난자완스",
        "explain": "쇠고기난자완스",
        "like": "",
      },
      {
        "cid": "새우딤섬",
        "image": "assets/images/새우 딤섬.jpg",
        "name": "새우딤섬",
        "explain": "새우딤섬",
        "like": "",
      },
      {
        "cid": "꽃빵",
        "image": "assets/images/꽃빵.jpg",
        "name": "꽃빵",
        "explain": "꽃빵",
        "like": "",
      },
      {
        "cid": "유산슬덮밥",
        "image": "assets/images/유산슬 덮밥.jpg",
        "name": "유산슬덮밥",
        "explain": "유산슬덮밥",
        "like": "",
      },
    ],
    "jp": [
      {
        "cid": "가츠동",
        "image": "assets/images/가츠동.jpg",
        "name": "가츠동",
        "explain": "가츠동",
        "like": "",
      },
      {
        "cid": "일식계란말이",
        "image": "assets/images/일식계란말이.jpg",
        "name": "일식계란말이",
        "explain": "일식계란말이",
        "like": "",
      },
      {
        "cid": "차슈",
        "image": "assets/images/차슈.jpg",
        "name": "차슈",
        "explain": "차슈",
        "like": "",
      },
      {
        "cid": "오꼬노미야끼",
        "image": "assets/images/오꼬노미야끼.jpg",
        "name": "오꼬노미야끼",
        "explain": "오꼬노미야끼",
        "like": "",
      },
      {
        "cid": "치킨가라아게",
        "image": "assets/images/치킨 가라아게.jpg",
        "name": "치킨가라아게",
        "explain": "치킨가라아게",
        "like": "",
      },
      {
        "cid": "새우튀김",
        "image": "assets/images/새우튀김.jpg",
        "name": "새우튀김",
        "explain": "새우튀김",
        "like": "",
      },
      {
        "cid": "규카츠",
        "image": "assets/images/규카츠.jpg",
        "name": "규카츠",
        "explain": "규카츠",
        "like": "",
      },
      {
        "cid": "유부우동",
        "image": "assets/images/유부우동.jpg",
        "name": "유부우동",
        "explain": "유부우동",
        "like": "",
      },
      {
        "cid": "야끼오니기리",
        "image": "assets/images/야끼 오니기리.jpg",
        "name": "야끼오니기리",
        "explain": "야끼오니기리",
        "like": "",
      },
      {
        "cid": "명란젓오차즈케",
        "image": "assets/images/명란젓 오차즈케.jpg",
        "name": "명란젓오차즈케",
        "explain": "명란젓오차즈케",
        "like": "",
      },
    ],
    "eu": [
      {
        "cid": "감바스",
        "image": "assets/images/감바스.jpg",
        "name": "감바스",
        "explain": "감바스",
        "like": "",
      },
      {
        "cid": "까르보나라",
        "image": "assets/images/까르보나라.jpg",
        "name": "까르보나라",
        "explain": "까르보나라",
        "like": "",
      },
      {
        "cid": "라따뚜이",
        "image": "assets/images/라따뚜이.jpg",
        "name": "라따뚜이",
        "explain": "라따뚜이",
        "like": "",
      },
      {
        "cid": "미트볼",
        "image": "assets/images/미트볼.jpg",
        "name": "미트볼",
        "explain": "미트볼",
        "like": "",
      },
      {
        "cid": "바베큐폭찹",
        "image": "assets/images/바베큐폭찹.jpg",
        "name": "바베큐폭찹",
        "explain": "바베큐폭찹",
        "like": "",
      },
      {
        "cid": "봉골레",
        "image": "assets/images/봉골레.jpg",
        "name": "봉골레",
        "explain": "봉골레",
        "like": "",
      },
      {
        "cid": "비프스튜",
        "image": "assets/images/비프스튜.jpg",
        "name": "비프스튜",
        "explain": "비프스튜",
        "like": "",
      },
      {
        "cid": "찹스테이크",
        "image": "assets/images/찹스테이크.jpg",
        "name": "찹스테이크",
        "explain": "찹스테이크",
        "like": "",
      },
      {
        "cid": "치즈오믈렛",
        "image": "assets/images/치즈오믈렛.jpg",
        "name": "치즈오믈렛",
        "explain": "치즈오믈렛",
        "like": "",
      },
      {
        "cid": "치킨그라탕",
        "image": "assets/images/치킨그라탕.jpg",
        "name": "치킨그라탕",
        "explain": "치킨그라탕",
        "like": "",
      },
      {
        "cid": "치킨커틀릿",
        "image": "assets/images/치킨커틀릿.jpg",
        "name": "치킨커틀릿",
        "explain": "치킨커틀릿",
        "like": "",
      },
      {
        "cid": "크림리조또",
        "image": "assets/images/크림리조또.jpg",
        "name": "크림리조또",
        "explain": "크림리조또",
        "like": "",
      },
      {
        "cid": "토마토스파게티",
        "image": "assets/images/토마토스파게티.jpg",
        "name": "토마토스파게티",
        "explain": "토마토스파게티",
        "like": "",
      },
      {
        "cid": "통감자치즈구이",
        "image": "assets/images/통감자 치즈구이.jpg",
        "name": "통감자치즈구이",
        "explain": "통감자치즈구이",
        "like": "",
      },
      {
        "cid": "핫윙",
        "image": "assets/images/핫윙.jpg",
        "name": "핫윙",
        "explain": "핫윙",
        "like": "",
      },
    ],
  };

  final Map<String, String> locationTypeToString = {
    "kr": "한식",
    "cn": "중식",
    "jp": "일식",
    "eu": "양식",
  };

  Future<List<Map<String, String>>> loadContentsFromLocation(
      String location) async {
    await Future.delayed(Duration(milliseconds: 1000));
    return data[location];
  }
}
